### PR TITLE
Switch to valid version of Minecraft 1.5

### PR DESCRIPTION
**Pull request by Techcable**
Looking at craftbukkit commit [83d29e461c](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/83d29e461c), it appears that the correct version is 1.5-R0.1-SNAPSHOT. A quick look at the craftbukkit versions available in [md-5 repo])(http://repo.md-5.net/content/groups/public/org/bukkit/craftbukkit/) confirms it.

### CODE REVIEW

**Comment by Europia79** [comment]
I'm pretty sure there are no public maven repositories of Craftbukkit anymore because of the DMCA. If you check your md-5 link... you'll see there's no JAR. What matters is what's in your local maven repository.

I actually changed that on purpose because of the meaning of SNAPSHOT... When you download a SNAPSHOT today, you're not guaranteed to get the same exact JAR tomorrow... because SNAPSHOT means *in development* or *in progress*. However, it doesn't seem right to me retain the label when development clearly stops.

But you're probably right... For the sake of standardization (across everyone's local repo), I should have retained the original label. What do you think ?

**Comment by Techcable** [comment]
[This craftbukkit commit](59dd2ddb9deb shows that the only 1.5.0 version is 1.5-R0.1-SNAPSHOT.

**Comment by Europia79** [comment]
Were you able to build VirtualPlayers ?

Do I need to change any other modules ?

**Comment by Techcable** [comment]
I'm trying to build it now, just wanted to share my change,

**Pull request merged**
